version: 1

formatters:
  brief:
    format: '%(message)s'
  
  default:
    format: '%(asctime)s - %(levelname)s - %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: /app/logs/voice.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
    level: NOTSET
    handlers: [console]

loggers:
  voice:
    level: DEBUG
    handlers: [console, info_file_handler]
    propagate: no